#
# Module manifest for module 'TFHelper'
#
# Generated by: Hyon
#
# Generated on: 4/1/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'TFHelper.PSModule.psm1'

# Version number of this module.
ModuleVersion = '3.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '912e4010-269e-46bb-8b47-8c739580843d'

# Author of this module
Author = 'Hyon'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = 'None'

# Description of the functionality provided by this module
Description = 'TFHelper Tool'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(  'tf-custom-invoke',
                        'tf-custom-webrequest',
                        'tf-login-switch',
                        'tf-module-import',
                        'tf-modules-cleanup',
                        'tf-modules-delete',
                        'tf-modules-get-list',
                        'tf-notification-delete',
                        'tf-notification-email-add',
                        'tf-notification-list',
                        'tf-notification-show',
                        'tf-notification-update',
                        'tf-run-do-apply',
                        'tf-run-do-cancel',
                        'tf-run-do-discard',
                        'tf-run-get-config-version',
                        'tf-run-get-detail',
                        'tf-run-get-recover-error-state',
                        'tf-run-get-plan-content',
                        'tf-run-get-plan-id',
                        'tf-run-get-plan-url',
                        'tf-run-get-policy-check',
                        'tf-run-get-status',
                        'tf-run-override-soft-policy',
                        'tf-special-get-workspace-children',
                        'tf-state-clean-up',
                        'tf-state-get-list',
                        'tf-state-migration',
                        'tf-state-recover',
                        'tf-teams-filter-by-name',
                        'tf-teams-get-list',
                        'tf-teams-get-team',
                        'tf-user-whoami',
                        'tf-workspace-get-current-run',
                        'tf-workspace-get-current-state',
                        'tf-workspace-get-current-state-file',
                        'tf-workspace-get-current-state-object',
                        'tf-workspace-get-id',
                        'tf-workspace-get-outputs',
                        'tf-workspace-get-resources',
                        'tf-workspace-put-state-version',
                        'tf-workspaces-do-apply',
                        'tf-workspaces-do-cancel',
                        'tf-workspaces-do-delete',
                        'tf-workspaces-do-destroy',
                        'tf-workspaces-do-discard',
                        'tf-workspaces-do-escape',
                        'tf-workspaces-do-policy-override',
                        'tf-workspaces-do-run',
                        'tf-workspaces-filter-by-name',
                        'tf-workspaces-filter-by-prefix',
                        'tf-workspaces-filter-by-status',
                        'tf-workspaces-get-list',
                        'tf-workspaces-get-plan-content'
                        'tf-workspaces-get-resource-count',
                        'tf-workspaces-get-version',
                        'tf-workspaces-get-workspace',
                        'tf-workspaces-lock',
                        'tf-workspaces-unlock',
                        'tf-workspaces-update-version'
                        )
}
